<?php

/**
 * @file
 * Contains sp_section.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sp_section_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sp_section module.
    case 'help.page.sp_section':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Creates the Section entity') . '</p>';
      return $output;

    default:
  }
}
