<?php

/**
 * @file
 * Contains sp_expire.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sp_expire_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sp_expire module.
    case 'help.page.sp_expire':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Handles the expiration of plans that require it.') . '</p>';
      return $output;

    default:
  }
}
