# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: wodby/drupal-php:7.2-dev-4.8.5

pipelines:
  default:
    - step:
        script:
          - echo "Composer prep"
          - composer global require drupal/coder:^8.2.12
          - composer global require dealerdirect/phpcodesniffer-composer-installer
          - composer global show -P
          - export PATH="$PATH:$HOME/.composer/vendor/bin"
          - composer install
          - phpcs -i
          - phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md --ignore=node_modules,bower_components,vendor web/modules/custom


