<?php

/**
 * @file
 * This files maps legacy content with the new structure.
 */

/**
 * Array containing the mapping needed to migrate content.
 */
const CONTENT_MAP = array(
  /**
   * II. Strategic Elements.
   *
   *  A. Economic, Workforce, and Workforce Development Activities Analysis
   *    1. Economic and Workforce Analysis
   *      A. Economic Analysis
   *        III. Employers’ Employment Needs.
   */
  "ac4bf4bd-a966-4aa0-94db-0a8a41026d07"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020026',
  ),
  /**
   * II. Strategic Elements.
   *
   *  A. Economic, Workforce, and Workforce Development Activities Analysis
   *    1. Economic and Workforce Analysis
   *      B. Workforce Analysis
   *        IV. Skill Gaps.
   */
  "36db23d0-e358-411e-be65-992f47004cbc"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020035',
  ),
  /**
   * II. Strategic Elements.
   *
   *  A. Economic, Workforce, and Workforce Development Activities Analysis
   *    2. Workforce Development, Education and Training Activities Analysis
   *      A. The State’s Workforce Development Activities.
   */
  "5a35f04b-5245-40aa-b7cb-ca1f50dd4682"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020042',
  ),
  /**
   * II. Strategic Elements.
   *
   *  A. Economic, Workforce, and Workforce Development Activities Analysis
   *    2. Workforce Development, Education and Training Activities Analysis
   *      B. The Strengths and Weaknesses of Workforce Development Activities.
   */
  "b4cff351-d9f4-43be-9a4f-218404658ee0"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020044',
  ),
  /**
   * II. Strategic Elements.
   *
   *  A. Economic, Workforce, and Workforce Development Activities Analysis
   *    2. Workforce Development, Education and Training Activities Analysis
   *      C. State Workforce Development Capacity.
   */
  "5f74601f-f778-4eb3-9d32-24695297f850"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020046',
  ),
  /**
   * II. Strategic Elements.
   *
   *  B. State Strategic Vision and Goals
   *    1. Vision.
   */
  "a1b9043a-ab71-4ae4-a68e-0095c238f4d9"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020110',
  ),
  /**
   * II. Strategic Elements.
   *
   *  B. State Strategic Vision and Goals
   *    2. Goals.
   */
  "07a797e1-cf4c-4aae-a079-ad0095b092a4"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020120',
  ),
  /**
   * II. Strategic Elements.
   *
   *  B. State Strategic Vision and Goals
   *    3. Performance Goals.
   */
  "97dafb0b-ac95-4e7f-be55-a4397adf723a"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020130',
  ),
  /**
   * II. Strategic Elements.
   *
   *  B. State Strategic Vision and Goals
   *    4. Assessment.
   */
  "9c30ea2e-3ef3-483d-b8b4-38fc90612929"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020140',
  ),
  /**
   * II. Strategic Elements.
   *
   *  C. State Strategy
   *    1. Describe the Strategies the State Will Implement, Including Industry
   *       or Sector Partnerships Related to In-demand Industry Sectors and
   *       Occupations and Career Pathways, as Required by WIOA Section
   *       101(d)(3)(b), (d). “career Pathway” is Defined at WIOA Section 3(7).
   *       “in-demand Industry Sector or Occupation” is Defined at WIOA
   *       Section 3(23).
   */
  "eb950485-bfef-467b-80a7-7d4afe5ad683"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020210',
  ),
  /**
   * II. Strategic Elements.
   *
   *  C. State Strategy
   *    2. Describe the Strategies the State Will Use to Align the Core
   *    Programs, Any Combined State Plan Partner Programs Included in This
   *    Plan, Required and Optional One-stop Partner Programs, and Any Other
   *    Resources Available to the State to Achieve Fully Integrated Customer
   *    Services Consistent with the Strategic Vision and Goals Described Above.
   *    Also Describe Strategies to Strengthen Workforce Development Activities
   *    in Regard to Weaknesses Identified in Section Ii(a)(2).
   */
  "d454d240-e815-4c27-9a7c-d46bcc907713"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020220',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    1. State Board Functions.
   */
  "13468393-3e92-4c7f-80e1-a80c42ae7e23"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030110',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      A. Core Program Activities to Implement the State’s Strategy.
   */
  "c30dca72-4d7d-4ef2-b7f2-e55445631021"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030122',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      B. Alignment with Activities Outside the Plan.
   */
  "5d84f6a7-f4c3-4e2d-be0f-b3310fe24e36"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030124',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      C. Coordination, Alignment and Provision of Services to Individuals.
   */
  "f9a1457b-da7a-4ccb-909c-4a219c616a26"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030128',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      D. Coordination, Alignment and Provision of Services to Employers.
   */
  "168e42ba-3b24-4b24-9a3a-ef6904f5d150"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030129',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      E. Partner Engagement with Educational Institutions.
   */
  "830aa644-6357-4345-9a57-46f52ba09b33"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030130',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      F. Partner Engagement with Other Education and Training Providers.
   */
  "efe2fcc4-05af-4edf-a4d9-46fd0e956ecd"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030139',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      G. Leveraging Resources to Increase Educational Access.
   */
  "ecb0e8a5-2e92-4682-9d05-f38a77070a89"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030140',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      H. Improving Access to Postsecondary Credentials.
   */
  "73107f29-bb34-4a75-a477-04cb6c15b16f"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030150',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      I. Coordinating with Economic Development Strategies.
   */
  "2a27d698-a149-40ab-bc3a-251422ffb4ab"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030160',
  ),
);
