<?php

/**
 * @file
 * This files maps legacy content with the new structure.
 */

/**
 * Array containing the mapping needed to migrate content.
 */
const CONTENT_MAP = array(
  /**
   * II. Strategic Elements.
   *
   *  A. Economic, Workforce, and Workforce Development Activities Analysis
   *    1. Economic and Workforce Analysis
   *      A. Economic Analysis
   *        III. Employers’ Employment Needs.
   */
  "ac4bf4bd-a966-4aa0-94db-0a8a41026d07"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020026',
  ),
  /**
   * II. Strategic Elements.
   *
   *  A. Economic, Workforce, and Workforce Development Activities Analysis
   *    1. Economic and Workforce Analysis
   *      B. Workforce Analysis
   *        IV. Skill Gaps.
   */
  "36db23d0-e358-411e-be65-992f47004cbc"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020035',
  ),
  /**
   * II. Strategic Elements.
   *
   *  A. Economic, Workforce, and Workforce Development Activities Analysis
   *    2. Workforce Development, Education and Training Activities Analysis
   *      A. The State’s Workforce Development Activities.
   */
  "5a35f04b-5245-40aa-b7cb-ca1f50dd4682"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020042',
  ),
  /**
   * II. Strategic Elements.
   *
   *  A. Economic, Workforce, and Workforce Development Activities Analysis
   *    2. Workforce Development, Education and Training Activities Analysis
   *      B. The Strengths and Weaknesses of Workforce Development Activities.
   */
  "b4cff351-d9f4-43be-9a4f-218404658ee0"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020044',
  ),
  /**
   * II. Strategic Elements.
   *
   *  A. Economic, Workforce, and Workforce Development Activities Analysis
   *    2. Workforce Development, Education and Training Activities Analysis
   *      C. State Workforce Development Capacity.
   */
  "5f74601f-f778-4eb3-9d32-24695297f850"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020046',
  ),
  /**
   * II. Strategic Elements.
   *
   *  B. State Strategic Vision and Goals
   *    1. Vision.
   */
  "a1b9043a-ab71-4ae4-a68e-0095c238f4d9"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020110',
  ),
  /**
   * II. Strategic Elements.
   *
   *  B. State Strategic Vision and Goals
   *    2. Goals.
   */
  "07a797e1-cf4c-4aae-a079-ad0095b092a4"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020120',
  ),
  /**
   * II. Strategic Elements.
   *
   *  B. State Strategic Vision and Goals
   *    3. Performance Goals.
   */
  "97dafb0b-ac95-4e7f-be55-a4397adf723a"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020130',
  ),
  /**
   * II. Strategic Elements.
   *
   *  B. State Strategic Vision and Goals
   *    4. Assessment.
   */
  "9c30ea2e-3ef3-483d-b8b4-38fc90612929"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020140',
  ),
  /**
   * II. Strategic Elements.
   *
   *  C. State Strategy
   *    1. Describe the Strategies the State Will Implement, Including Industry
   *       or Sector Partnerships Related to In-demand Industry Sectors and
   *       Occupations and Career Pathways, as Required by WIOA Section
   *       101(d)(3)(b), (d). “career Pathway” is Defined at WIOA Section 3(7).
   *       “in-demand Industry Sector or Occupation” is Defined at WIOA
   *       Section 3(23).
   */
  "eb950485-bfef-467b-80a7-7d4afe5ad683"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020210',
  ),
  /**
   * II. Strategic Elements.
   *
   *  C. State Strategy
   *    2. Describe the Strategies the State Will Use to Align the Core
   *    Programs, Any Combined State Plan Partner Programs Included in This
   *    Plan, Required and Optional One-stop Partner Programs, and Any Other
   *    Resources Available to the State to Achieve Fully Integrated Customer
   *    Services Consistent with the Strategic Vision and Goals Described Above.
   *    Also Describe Strategies to Strengthen Workforce Development Activities
   *    in Regard to Weaknesses Identified in Section Ii(a)(2).
   */
  "d454d240-e815-4c27-9a7c-d46bcc907713"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000020220',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    1. State Board Functions.
   */
  "13468393-3e92-4c7f-80e1-a80c42ae7e23"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030110',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      A. Core Program Activities to Implement the State’s Strategy.
   */
  "c30dca72-4d7d-4ef2-b7f2-e55445631021"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030122',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      B. Alignment with Activities Outside the Plan.
   */
  "5d84f6a7-f4c3-4e2d-be0f-b3310fe24e36"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030124',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      C. Coordination, Alignment and Provision of Services to Individuals.
   */
  "f9a1457b-da7a-4ccb-909c-4a219c616a26"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030128',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      D. Coordination, Alignment and Provision of Services to Employers.
   */
  "168e42ba-3b24-4b24-9a3a-ef6904f5d150"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030129',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      E. Partner Engagement with Educational Institutions.
   */
  "830aa644-6357-4345-9a57-46f52ba09b33"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030130',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      F. Partner Engagement with Other Education and Training Providers.
   */
  "efe2fcc4-05af-4edf-a4d9-46fd0e956ecd"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030139',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      G. Leveraging Resources to Increase Educational Access.
   */
  "ecb0e8a5-2e92-4682-9d05-f38a77070a89"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030140',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      H. Improving Access to Postsecondary Credentials.
   */
  "73107f29-bb34-4a75-a477-04cb6c15b16f"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030150',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  A. State Strategy Implementation
   *    2. Implementation of State Strategy
   *      I. Coordinating with Economic Development Strategies.
   */
  "2a27d698-a149-40ab-bc3a-251422ffb4ab"  => array(
    'grant_award_id' => '33174',
    'form_id' => '2001',
    'row' => '000030160',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies.
   */
  // "2374aeba-b9f5-4304-84e9-6d4cdb44a5aa"  => array(
  // 'grant_award_id' => '33174',
  // 'form_id' => '2001',
  // 'row' => '000030160',
  // ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    1. the State Operating Systems That Will Support the Implementation of
   *       the State’s Strategies. This Must Include a Description Of–
   *      A. State Operating Systems That Support Coordinated Implementation of
   *         State Strategies (e.g., Labor Market Information Systems, Data
   *         Systems, Communication Systems, Case-management Systems, Job Banks,
   *         Etc.).
   */
  "dedca747-d32a-4484-97ea-4e16777d8e14"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030213',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    1. the State Operating Systems That Will Support the Implementation of
   *       the State’s Strategies. This Must Include a Description Of–
   *      B. Data-collection and Reporting Processes Used for All Programs and
   *         Activities, Including Those Present in One-stop Centers.
   */
  "0a817401-083f-4215-b85b-9193972cfdd4"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030216',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    2. the State Policies That Will Support the Implementation of the
   *       State’s Strategies (e.g., Co-enrollment Policies and Universal
   *       Intake Processes Where Appropriate). in Addition, Describe the
   *       State’s Process for Developing Guidelines for State-administered
   *       One-stop Partner Programs’ Contributions to a One-stop Delivery
   *       System, Including Benchmarks, and Its Guidance to Assist Local
   *       Boards, Chief Elected Officials, and Local One-stop Partners in
   *       Determining Equitable and Stable Methods of Funding Infrastructure
   *       in Accordance with Sec. 121(h)(1)(b). Beginning with the State Plan
   *       Modification in 2018 and for Subsequent State Plans and State Plan
   *       Modifications, the State Must Also Include Such Guidelines.
   */
  "371c0537-a1e7-4285-88fa-4b231b26b55b"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030218',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    3. State Program and State Board Overview.
   *      A. State Agency Organization.
   */
  "a02fec1d-c00b-49e6-b2dd-50ffba236a1e"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030230',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    3. State Program and State Board Overview.
   *      B. State Board.
   */
  "85badacd-8b59-4096-8388-45812961c541"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030240',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    3. State Program and State Board Overview.
   *      B. State Board
   *        I. Membership Roster.
   */
  "6cd3f19d-8b93-4ed9-b6de-6626e46d1828"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030241',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    3. State Program and State Board Overview.
   *      B. State Board
   *        II. Board Activities.
   */
  "8194aeba-daf9-4c64-8325-3731d81287a8"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030250',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    4. Assessment and Evaluation of Programs and One-stop Program Partners.
   *      A. Assessment of Core Programs.
   */
  "5c0b5889-1bd8-4c81-b106-346493fc0574"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030262',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    4. Assessment and Evaluation of Programs and One-stop Program Partners.
   *      B. Assessment of One-stop Partner Programs.
   */
  "6d34e9a5-9912-4237-ac27-7e973dba932f"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030264',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    4. Assessment and Evaluation of Programs and One-stop Program Partners.
   *      C. Previous Assessment Results.
   */
  "e6295171-3d4b-44c2-a8e5-fb446f37fe77"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030265',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    4. Assessment and Evaluation of Programs and One-stop Program Partners.
   *      D. Evaluation.
   */
  "2ca964e9-6b95-4c7b-8de4-f0bcc0d56294"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030267',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    5. Distribution of Funds for Core Programs
   *      A. for Title I Programs.
   */
//  "54434269-2bf3-4ede-b84a-024f84f0de1a"  => array(
//    'grant_award_id' => '33144',
//    'form_id' => '2001',
//    'row' => '000030271',
//  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    5. Distribution of Funds for Core Programs
   *      A. for Title I Programs
   *        I. Youth Activities in Accordance with WIOA Section 128(b)(2) or
   *           (b)(3),.
   */
  "ad9b456d-2843-4bed-b173-af144088806b"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030271',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    5. Distribution of Funds for Core Programs
   *      A. for Title I Programs
   *        II. Adult and Training Activities in Accordance with WIOA Section
   *        133(b)(2) or (b)(3),.
   */
  "d5e7c226-4e5b-4017-98de-19e73d6d116d"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030272',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    5. Distribution of Funds for Core Programs
   *      A. for Title I Programs
   *        III. Dislocated Worker Employment and Training Activities in
   *        Accordance with WIOA Section 133(b)(2) and Based on Data and
   *        Weights Assigned.
   */
  "7dc64739-5a0a-4b36-b181-ea3af8e3a4be"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030273',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    5. Distribution of Funds for Core Programs
   *      B. For Title II
   *        I. Multi-year Grants or Contracts.
   */
  "c6497b66-86e0-444e-990e-e0c516c55bf2"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030275',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    5. Distribution of Funds for Core Programs
   *      B. For Title II
   *        II. Ensure Direct and Equitable Access.
   */
  "1f89b823-48bf-43af-8347-c4f5f9ffa93a"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030276',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    5. Distribution of Funds for Core Programs
   *      C. Title IV Vocational Rehabilitation.
   */
  "28d57b6d-bed0-4f35-a6a7-3d1ffc3ca6d5"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030279',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    6. Program Data
   *      A. Data Alignment and Integration
   *        I. Describe the State’s Plans to Make the Management Information
   *           Systems for the Core Programs Interoperable to Maximize the
   *           Efficient Exchange of Common Data Elements to Support Assessment
   *           and Evaluation.
   */
  "374cc473-4c2e-42f2-910a-645dda479816"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030282',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    6. Program Data
   *      A. Data Alignment and Integration
   *        II. Describe the State’s Plans to Integrate Data Systems to
   *            Facilitate Streamlined Intake and Service Delivery to Track
   *            Participation Across All Programs Included in This Plan.
   */
  "aef85f6c-158c-4f93-b07f-26f0b1e685e9"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030283',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    6. Program Data
   *      A. Data Alignment and Integration
   *        III. Explain How the State Board Will Assist the Governor in
   *             Aligning Technology and Data Systems Across Required One-stop
   *             Partner Programs (including Design and Implementation of Common
   *             Intake, Data Collection, Etc.) and How Such Alignment Will
   *             Improve Service Delivery to Individuals, Including Unemployed
   *             Individuals.
   */
  "3604fcca-e17d-460c-8271-0a7f41a26c9e"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030285',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    6. Program Data
   *      A. Data Alignment and Integration
   *        IV. Describe the State’s Plans to Develop and Produce the Reports
   *            Required Under Section 116, Performance Accountability System.
   *            (wioa Section 116(d)(2)).
   */
  "1c88a792-0796-4bcb-8b2a-f7e92d8ecbd2"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030290',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    6. Program Data
   *      B. Assessment of Participants’ Post-program Success.
   */
  "f41d0d39-0450-4077-901a-267ba95fc0c4"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030300',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    6. Program Data
   *      C. Use of Unemployment Insurance (ui) Wage Record Data.
   */
  "cca4b265-9ae9-42c9-866e-3865574a63bb"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030320',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    6. Program Data
   *      D. Privacy Safeguards.
   */
  "ce65a1ef-7777-4334-bfc1-a745ad579d70"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030330',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    7. Priority of Service for Veterans.
   */
  "d480f993-db6b-4fb7-8505-348b9a8a7b2d"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030340',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    8. Addressing the Accessibility of the One-stop Delivery System for
   *       Individuals with Disabilities.
   */
  "5c69af70-956e-4038-bf66-608183da2887"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030350',
  ),
  /**
   * III. Operational Planning Elements.
   *
   *  B. State Operating Systems and Policies
   *    9. Addressing the Accessibility of the One-stop Delivery System for
   *       English Language Learners.
   */
  "2a65b0a4-7ae9-41d6-a62a-f2dd2e22e754"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030355',
  ),
  /**
   * IV. Coordination with State Plan Programs.
   */
  "bab508e6-72b9-4152-83e0-9f9c1ba4ea21"  => array(
    'grant_award_id' => '33144',
    'form_id' => '2001',
    'row' => '000030390',
  ),
  /**
   * V. Common Assurances (for all core programs).
   */
  // These are all Yes/no Questions manual migration required.
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    A. General Requirements
   *      1. Regions and Local Workforce Development Areas
   *        A. Identify the Regions and the Local Workforce Development Areas
   *           Designated in the State.
   */
  "03d01961-b1a6-4ebd-aa88-1188587f6246"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040030',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    A. General Requirements
   *      1. Regions and Local Workforce Development Areas
   *        B. Describe the Process Used for Designating Local Areas, Including
   *           Procedures for Determining Whether the Local Area Met the
   *           Criteria for “performed Successfully” and “sustained Fiscal
   *           Integrity” in Accordance with 106(b)(2) and (3) of Wioa.
   *           Describe the Process Used for Identifying Regions and Planning
   *           Regions Under Section 106(a) of Wioa. This Must Include a
   *           Description of How the State Consulted with the Local Boards
   *           and Chief Elected Officials in Identifying the Regions.
   */
  "9986c4bd-9427-4b7d-8894-62eb0c12d8e7"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040040',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    A. General Requirements
   *      1. Regions and Local Workforce Development Areas
   *        C. Provide the Appeals Process Referred to in Section 106(b)(5) of
   *           WIOA Relating to Designation of Local Areas.
   */
  "f83f9e67-fc02-4645-88ac-f1fe795866ae"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040050',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    A. General Requirements
   *      1. Regions and Local Workforce Development Areas
   *        D. Provide the Appeals Process Referred to in Section 121(h)(2)(e)
   *           of WIOA Relating to Determinations for Infrastructure Funding.
   */
  "dc6386fa-addf-42ca-82e1-42cda8084a47"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040060',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    A. General Requirements
   *      2. Statewide Activities
   *        A. Provide State Policies or Guidance for the Statewide Workforce
   *           Development System and for Use of State Funds for Workforce
   *           Investment Activities.
   */
  "92062fe4-be8b-4288-ad18-0a6a869d8127"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040110',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    A. General Requirements
   *      2. Statewide Activities
   *        B. Describe How the State Intends to Use Governor’s Set Aside
   *           Funding. Describe How the State Will Utilize Rapid Response
   *           Funds to Respond to Layoffs and Plant Closings and Coordinate
   *           Services to Quickly Aid Companies and Their Affected Workers.
   *           States Also Should Describe Any Layoff Aversion Strategies
   *           They Have Implemented to Address at Risk Companies and Workers.
   */
  "b4398428-8402-4b76-bfdc-5464e21ec361"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040120',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    A. General Requirements
   *      2. Statewide Activities
   *        C. In Addition, Describe the State Policies and Procedures to
   *           Provide Rapid Responses in Cases of Natural Disasters Including
   *           Coordination with Fema and Other Entities.
   */
  "118df503-c58d-49e4-9bd0-01a31529f023"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040130',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    A. General Requirements
   *      2. Statewide Activities
   *        D. Describe How the State Provides Early Intervention
   *           (e.g., Rapid Response) to Worker Groups on Whose Behalf a Trade
   *           Adjustment Assistance (taa) Petition Has Been Filed.
   *           (section 134(a)(2)(a).) This Description Must Include How the
   *           State Disseminates Benefit Information to Provide Trade-affected
   *           Workers in the Groups Identified in the Taa Petitions with an
   *           Accurate Understanding of the Provision of Taa Benefits and
   *           Services in Such a Way That They Are Transparent to the
   *           Trade-affected Dislocated Worker Applying for Them (trade Act
   *           Sec. 221(a)(2)(a) and Sec. 225; Governor- Secretary Agreement).
   *           Describe How the State Will Use Funds That Have Been Reserved for
   *           Rapid Response to Provide Services for Every Worker Group That
   *           Files a Taa Petition.
   */
  "069b24f4-3d57-4db6-b952-9077278f9094"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040140',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    B. Adult and Dislocated Workers Program Requirements
   *      1. If the State is Utilizing Work-based Training Models
   *         (e.g. On-the- Job Training, Incumbent Worker Training,
   *         Transitional Jobs, and Customized Training) as Part of Its
   *         Training Strategy and These Strategies Are Not Already Discussed
   *         in Other Sections of the Plan, Describe the State’s Strategies for
   *         How These Models Ensure High Quality Training for Both the
   *         Participant and the Employer.
   */
  "151ef573-d130-4298-972f-d7669e4cf8bc"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040210',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    B. Adult and Dislocated Workers Program Requirements
   *      2. Describe How the State Will Incorporate Registered Apprenticeship
   *         into Its Strategy and Services.
   */
  "7881bc23-9034-400a-88e2-7e3af1a1b21f"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040220',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    B. Adult and Dislocated Workers Program Requirements
   *      3. Provide the Procedure, Eligibility Criteria, and Information
   *         Requirements for Determining Training Provider Initial and
   *         Continued Eligibility, Including Registered Apprenticeship
   *         Programs (wioa Section 122).orporate Registered Apprenticeship.
   */
  "50ac7224-a1fe-4822-b6a1-76ca87f9c0af"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040230',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    B. Adult and Dislocated Workers Program Requirements
   *      4. Describe How the State Will Implement and Monitor the Priority
   *         for Public Assistance Recipients, Other Low-income Individuals,
   *         and Individuals Who Are Basic Skills Deficient in Accordance
   *         with the Requirements of WIOA Sec. 134(c)(3)(e), Which Applies
   *         to Individualized Career Services and Training Services Funding
   *         by the Adult Formula Program.
   */
  "f1d9b8da-6c1b-4e29-a551-1a94109a0163"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040240',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    B. Adult and Dislocated Workers Program Requirements
   *      5. Describe the State’s Criteria Regarding Local Area Transfer of
   *         Funds Between the Adult and Dislocated Worker Programs.
   */
  "0627092d-4230-4217-ab55-a262dce743e9"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040250',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    C. Youth Program Requirements
   *      1. Identify the State-developed Criteria to Be Used by Local Boards
   *         in Awarding Grants for Youth Workforce Investment Activities
   *         and Describe How the Local Boards Will Take into Consideration
   *         the Ability of the Providers to Meet Performance Accountability
   *         Measures Based on Primary Indicators of Performance for the
   *         Youth Program as Described in Section 116(b)(2)(a)(ii) of WIOA
   *         in Awarding Such Grants.
   */
  "4ab7b387-53e1-49d3-b95b-26b485df54c0"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040311',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    C. Youth Program Requirements
   *      2. Describe the Strategies the State Will Use to Achieve Improved
   *         Outcomes for Out-of-school Youth as Described in 129(a)(1)(b),
   *         Including How it Will Leverage and Align the Core Programs,
   *         and Combined State Plan Partner Programs Included in This Plan,
   *         Required and Optional One-stop Partner Programs, and Any Other
   *         Resources Available.
   */
  "1ec1308a-f3e7-4db1-a79b-6ba231100f07"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040318',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    C. Youth Program Requirements
   *      3. Describe How the State Will Ensure That All 14 Program Elements
   *         Described in WIOA Section 129(c)(2) Are Made Available and
   *         Effectively Implemented.
   */
  "e67b6944-4910-4698-b119-f9d002df0a37"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040321',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    C. Youth Program Requirements
   *      4. Provide the Language Contained in the State Policy for
   *         “requiring Additional Assistance to Enter or Complete
   *         an Educational Program, or to Secure and Hold Employment”
   *         Criterion for Out-of-school Youth Specified in WIOA
   *         Section 129(a)(1)(b)(iii)(viii) and for “requiring
   *         Additional Assistance to Complete an Education
   *         Program, or to Secure and Hold Employment” Criterion
   *         for In- School Youth Specified in WIOA Section
   *         129(a)(1)(c)(iv)(vii).
   */
  "a962a5cf-06e0-4492-9353-84eec33416dc"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040330',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    C. Youth Program Requirements
   *      5. Include the State Definition, as Defined in Law, for Not Attending
   *         School and Attending School as Specified in WIOA Section
   *         129(a)(1)(b)(i) and Section 129(a)(1)(c)(i). if State Law
   *         Does Not Define “not Attending School” or “attending
   *         School” Indicate That is the Case.
   */
  "590835c8-1f8a-4a82-8e9a-f3b610a081d1"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040350',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    C. Youth Program Requirements
   *      6. If Not Using the Basic Skills Deficient Definition Contained in
   *         WIOA Section 3(5)(b), Include the Specific State Definition.
   */
  "91b421cb-402e-4211-a22f-7f83a707f3e4"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040360',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    D. Single-area State Requirements.
   *      1. Any Comments from the Public Comment Period That Represent
   *         Disagreement with the Plan. (wioa Section 108(d)(3).)
   *      2. The Entity Responsible for the Disbursal of Grant Funds,
   *         as Determined by the Governor, if Different from That for the
   *         State. (wioa Section 108(b)(15).)
   *      3. The Type and Availability of WIOA Title I Youth Activities,
   *         Including an Identification of Successful Providers of Such
   *         Activities. (wioa Section 108(b)(9).)
   */
  "c03ba9ec-ee90-4d63-8b37-7ab83fc19fc9"  => array(
    'grant_award_id' => '32718',
    'form_id' => '2002',
    'row' => '000040360',
  ),
  /**
   * VI. Program-specific Requirements for Core Programs.
   *
   *  Program-specific Requirements for Adult, Dislocated Worker, and Youth
   *  Activities under Title I-B
   *    D. Single-area State Requirements.
   *      4. A Description of the Roles and Resource Contributions of the
   *         One-stop Partners.

   */

);
