<?php

/**
 * @file
 * Contains sp_plan_year.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function sp_plan_year_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sp_plan_year module.
    case 'help.page.sp_plan_year':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Creates the Plan Year entity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_operation().
 */
function sp_plan_year_entity_operation(EntityInterface $entity) {
  if ($entity->hasLinkTemplate('wizard')) {
    return [
      'wizard' => [
        'title' => t('Wizard'),
        'weight' => 50,
        'url' => $entity->toUrl('wizard'),
      ],
    ];
  }

  return [];
}

/**
 * Implements hook_entity_type_alter().
 */
function sp_plan_year_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityType[] $entity_types */
  foreach ($entity_types as $entity_type_id => $entity_type) {
    if ($entity_type_id === 'plan_year') {
      $entity_type->setLinkTemplate('wizard', '/admin/structure/plan_year/{plan_year}/wizard');
    }
  }
}
