<?php

/**
 * @file
 * Contains sp_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\sp_create\PlanYearInfo;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_help().
 */
function sp_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sp_field module.
    case 'help.page.sp_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Alter or create fields on the site.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function sp_field_entity_extra_field_info() {
  $extra = [];
  $extra['node'][PlanYearInfo::SPY_BUNDLE]['display']['plan_year_view'] = [
    'label' => t('View a plan year'),
    'description' => t('Allows the display of an entire plan year.'),
    'weight' => 100,
    'visible' => TRUE,
  ];
  $extra['node'][PlanYearInfo::SPY_BUNDLE]['display']['plan_year_toc'] = [
    'label' => t('View a plan year TOC'),
    'description' => t('Allows the display of a plan year table of contents.'),
    'weight' => 101,
    'visible' => TRUE,
  ];
  $extra['node'][PlanYearInfo::SPYS_BUNDLE]['display']['plan_year_section_view'] = [
    'label' => t('View a plan year section'),
    'description' => t('Allows the display of a plan year section.'),
    'weight' => 101,
    'visible' => TRUE,
  ];

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function sp_field_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('plan_year_view')) {
    $build['plan_year_view'] = [
      '#theme' => 'sp_display_plan_year_view',
      '#node' => $entity,
    ];
  }
  if ($display->getComponent('plan_year_toc')) {
    $build['plan_year_toc'] = [
      '#theme' => 'sp_display_plan_year_toc',
      '#node' => $entity,
    ];
  }
  if ($display->getComponent('plan_year_section_view')) {
    $build['plan_year_section_view'] = [
      '#theme' => 'sp_display_plan_year_section_view',
      '#node' => $entity,
    ];
  }
}
