<?php

/**
 * @file
 * Contains sp_display.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sp_display_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sp_display module.
    case 'help.page.sp_display':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Handles displaying content.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function sp_display_theme() {
  $base = [
    'file' => 'sp_display.theme.inc',
  ];
  $themes = [
    'sp_display_plan_year_view' => [
      'variables' => ['node' => NULL],
    ],
    'sp_display_plan_year_toc' => [
      'variables' => ['node' => NULL],
    ],
    'sp_display_plan_year_section_view' => [
      'variables' => ['node' => NULL],
    ],
    'sp_display_download_plan_form' => [
      'variables' => ['node' => NULL, 'orientation' => NULL],
    ],
    'sp_display_plan_type_badge' => [
      'variables' => ['node' => NULL],
    ],
  ];
  foreach ($themes as &$theme) {
    $theme += $base;
  }
  return $themes;
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @all_plans
 */
function sp_display_preprocess_views_view(&$variables) {
  if ($variables['view']->id() !== 'all_plans_6') {
    return;
  }
  if (empty($variables['attachment_before'])) {
    $variables['attachment_before'] = [];
  }
  $variables['attachment_before'][] = [
    '#type' => 'markup',
    '#markup' => '<div class="results-title"><h3>' . t('All Plans') . '</h3></div>',
    '#weight' => 0,
  ];
}
